import Head from 'next/head';
import Canvas from '../components/canvas';
import styles from '../styles/Home.module.scss';

export default function Home() {
    const clearCanvas = () => {
        const canvas: HTMLCanvasElement = document.getElementById(
            'myCanvas',
        ) as HTMLCanvasElement;
        canvas.width += 0;
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>5Drawings</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Bem vindo ao <a href="https://nextjs.org">5Drawings!</a>
                </h1>

                <p className={styles.description}>
                    Desenhos treinados: olho, peixe, diamante, borboleta e
                    melância.
                </p>

                <span className={styles.description}>
                    <i>O seu desenho é um: Peixe</i>
                </span>

                <Canvas width={500} height={500} />

                <button className={styles.button} onClick={clearCanvas}>
                    Limpar
                </button>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://github.com/yankelvin"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered By Yan Kelvin
                </a>
            </footer>
        </div>
    );
}
